CREATE TABLE dbo.Projects
(
   Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Projects PRIMARY KEY,
   Title NVARCHAR(100) NOT NULL,
   Description NVARCHAR(1000) NOT NULL CONSTRAINT DF_Projects_Description DEFAULT (''),
   CreatedUtc DATETIME2 NOT NULL CONSTRAINT DF_Projects_CreatedUtc DEFAULT (GETUTCDATE())
);
